// app/reviews/[slug]/page.js
import { getReviewBySlug } from '@/lib/markdown';
import ReactMarkdown from 'react-markdown';
import { notFound } from 'next/navigation';
import JsonLd from '@/components/JsonLd';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
// Changed import from vscDarkPlus to prism for lighter colors
import { prism } from 'react-syntax-highlighter/dist/cjs/styles/prism';

// 1. Dynamic SEO Metadata Generation
export async function generateMetadata({ params }) {
  const resolvedParams = await params;
  const review = await getReviewBySlug(resolvedParams.slug);

  if (!review) return { title: 'Review Not Found' };

  // 1. Convert the comma-separated keywords string into a proper array
  const keywordArray = review.frontmatter.metaKeywords 
    ? review.frontmatter.metaKeywords.split(',').map(k => k.trim())
    : [review.frontmatter.title, 'Review', 'Pricing', 'B2B SaaS'];

  return {
    // 2. Use the custom SEO fields, or fall back to the defaults
    title: review.frontmatter.metaTitle || `${review.frontmatter.title} Review`, 
    description: review.frontmatter.metaDescription || review.frontmatter.summary,
    keywords: keywordArray,
  };
}

// 2. The Page Component
export default async function ReviewPage({ params }) {
  const resolvedParams = await params;
  const review = await getReviewBySlug(resolvedParams.slug);

  if (!review) notFound(); // Triggers 404 if the markdown file doesn't exist

  const { frontmatter, content } = review;

  return (
    <main className="max-w-3xl mx-auto py-12 px-6">
      {/* Inject the SEO Schema for Star Ratings */}
      <JsonLd 
        softwareName={frontmatter.title.split(' Review')[0]} 
        rating={frontmatter.rating}
        reviewCount={frontmatter.reviewCount}
        price={frontmatter.price}
        currency="USD"
        category="BusinessApplication"
      />

      <article>
        <header className="mb-10 border-b pb-8">
          <h1 className="text-4xl md:text-5xl font-extrabold text-gray-900 mb-6 tracking-tight">
            {frontmatter.title}
          </h1>
          <div className="flex flex-wrap items-center gap-4 text-gray-600">
            <span className="bg-blue-100 text-blue-800 px-3 py-1 rounded-full text-sm font-semibold">
              ⭐ {frontmatter.rating} / 5
            </span>
            <span className="text-sm font-medium">Published: {frontmatter.date}</span>
            <span className="text-sm font-medium">Starting at ${frontmatter.price}/mo</span>
          </div>
        </header>

        {/* This is where the magic happens.
          The 'prose' class from Tailwind Typography automatically styles 
          the raw HTML generated by ReactMarkdown!
        */}
        <div className="prose prose-lg prose-blue max-w-none text-gray-800">
        <ReactMarkdown
          components={{
            code({ node, inline, className, children, ...props }) {
              const match = /language-(\w+)/.exec(className || '');
              return !inline && match ? (
                <SyntaxHighlighter
                  {...props}
                  // Updated style prop to use the prism light theme
                  style={prism}
                  language={match[1]}
                  PreTag="div"
                  className="rounded-lg !my-6 text-sm border border-gray-200"
                >
                  {String(children).replace(/\n$/, '')}
                </SyntaxHighlighter>
              ) : (
                <code {...props} className="bg-gray-100 px-1 py-0.5 rounded text-blue-600 font-mono text-sm">
                  {children}
                </code>
              );
            },
          }}
        >
          {content}
        </ReactMarkdown>
        </div>
      </article>
    </main>
  );
}